---
- name: Ansible debug module
  hosts: cisco_switches
  vars_files:
    - ../vars/cisco_switches.yml
  tasks:
    - name: Print ansible_facts
      ansible.builtin.debug:
        msg:
          - "{{ ansible_facts }}"

    - name: Print custom message
      ansible.builtin.debug:
        msg:
          - "Switch name is {{ ansible_facts.net_hostname }}"
          - "Switch OS is {{ ansible_facts.net_iostype }}"
          - "Switch model is {{ ansible_facts.net_model }}"
          - "Test varible is {{ test_var }}"

# Sadece ansible_facts degiskenini debug ile yazdirir.