---
- name: Check golden config
  hosts: cisco_switches
  gather_facts: false
  tasks:
    - name: Check drift against golden config
      cisco.ios.ios_config:
        lines: "ip domain-name golden-retriever.com"
        diff_against: intended
        intended_config: "{{ lookup('file', '/root/ansible1/golden/cisco_sw_golden_config.cfg') }}"
      register: result

