---
- name: playbook creates a vlan
  hosts: cisco_switches
  gather_facts: no

  tasks:
    - name: create vlan
      cisco.ios.ios_config:
        lines:
          - vlan 10
          - name VLAN101
          - vlan 20
          - name VLAN201
