---
- name: IOS Command Wait For
  hosts: cisco_switches
  gather_facts: false
  tasks:
    - name: Command with prompt
      cisco.ios.ios_command:
        commands: 
          - command: clear counters GigabitEthernet1/0/2
            prompt: 'Clear "show interface" counters on this interface \[confirm\]'
            answer: 'y'
      register: clear_counter

    - name: Print clear counter
      ansible.builtin.debug:
        msg: "Clear Counter is ---- {{ clear_counter }}" 

    - name: Execute show interface
      cisco.ios.ios_command:
        commands: show interface GigabitEthernet1/0/2
      register: show_output

    - name: Print show_output
      ansible.builtin.debug:
        msg: " show_output is ---- {{ show_output }}" 